import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightSidebarTopics from 'starlight-sidebar-topics';

export default defineConfig({
  site: 'https://refgenie.org',
  integrations: [
    starlight({
      title: 'Refgenie',
      logo: {
        light: './public/img/refgenie_bug.svg',
        dark: './public/img/refgenie_bug_light.svg',
      },
      favicon: '/img/refgenie_bug.svg',
      editLink: {
        baseUrl: 'https://github.com/refgenie/refgenie-docs/edit/master/docs/',
      },
      customCss: ['./src/styles/custom.css'],
      components: {
        PageTitle: './src/components/PageTitle.astro',
        SiteTitle: './src/components/SiteTitle.astro',
        EditLink: './src/components/EditLink.astro',
        Footer: './src/components/Footer.astro',
      },
      plugins: [
        starlightSidebarTopics([
          {
            label: 'Refgenie',
            link: '/refgenie/',
            icon: 'open-book',
            items: [
              {
                label: 'Getting started',
                items: [
                  { label: 'Introduction', slug: 'refgenie' },
                  { label: 'What\'s new in v1', slug: 'refgenie/whats_new' },
                  { label: 'Overview', slug: 'refgenie/overview' },
                  { label: 'Install', slug: 'refgenie/install' },
                  { label: 'Configure', slug: 'refgenie/configuration' },
                  { label: 'CLI tutorial', slug: 'refgenie/cli_tutorial' },
                  { label: 'Genome initialization', slug: 'refgenie/genome_tutorial' },
                  { label: 'Citing refgenie', slug: 'refgenie/manuscripts' },
                ],
              },
              {
                label: 'How-to guides',
                items: [
                  { label: 'Refer to assets', slug: 'refgenie/asset_registry_paths' },
                  { label: 'Download pre-built assets', slug: 'refgenie/pull' },
                  { label: 'Use refgenie from Python', slug: 'refgenie/notebooks/refgenie' },
                  { label: 'Use refgenie from Python (API)', slug: 'refgenie/refgenie_object' },
                  { label: 'Use data channels', slug: 'refgenie/data_channels' },
                  { label: 'Build assets', slug: 'refgenie/build' },
                  { label: 'Stage assets for serving', slug: 'refgenie/staging' },
                  { label: 'Configure remote storage', slug: 'refgenie/remotes' },
                  { label: 'Building and serving tutorial', slug: 'refgenie/building_tutorial' },
                  { label: 'Retrieve paths to assets', slug: 'refgenie/seek' },
                  { label: 'Compare genomes', slug: 'refgenie/compare' },
                  { label: 'Add custom assets', slug: 'refgenie/custom_assets' },
                  { label: 'Manage aliases', slug: 'refgenie/alias' },
                  { label: 'Managing asset groups and naming', slug: 'refgenie/naming_assets' },
                  { label: 'Populate refgenie paths', slug: 'refgenie/populate' },
                  { label: 'Set up your own data channel', slug: 'refgenie/set_up_data_channel' },
                  { label: 'Run a server', slug: 'refgenie/server_tutorial' },
                  { label: 'Use the dashboard', slug: 'refgenie/dash' },
                  { label: 'Connect the web UI to your local refgenie', slug: 'refgenie/bridge' },
                  { label: 'Use refgenie with AI', slug: 'refgenie/use_with_ai' },
                  { label: 'Connect AI assistants (MCP)', slug: 'refgenie/mcp' },
                ],
              },
              {
                label: 'Server',
                items: [
                  { label: 'Intro', slug: 'refgenie/server' },
                  { label: 'Serving modes', slug: 'refgenie/serving_modes' },
                  { label: 'Public servers', slug: 'refgenie/servers' },
                  { label: 'Data channels', slug: 'refgenie/server/data_channels' },
                  { label: 'Remotes', slug: 'refgenie/server/remotes' },
                  { label: 'Persisting download stats', slug: 'refgenie/server/endpoint_hits_collector' },
                  { label: 'Pagination and search', slug: 'refgenie/server/pagination_and_search' },
                ],
              },
              {
                label: 'Reference',
                items: [
                  { label: 'Glossary', slug: 'refgenie/glossary' },
                  { label: 'Database backends', slug: 'refgenie/database' },
                  { label: 'Flexible asset types', slug: 'refgenie/flexible_asset_types' },
                  { label: 'Studies using refgenie', slug: 'refgenie/uses_refgenie' },
                  { label: 'Recipe specification', slug: 'refgenie/recipe_specification' },
                  { label: 'Asset class specification', slug: 'refgenie/asset_class_specification' },
                  { label: 'FAQ', slug: 'refgenie/faq' },
                  { label: 'Contributing', slug: 'refgenie/contributing' },
                ],
              },
            ],
          },
          {
            label: 'Refget',
            link: '/refget/',
            icon: 'open-book',
            items: [
              {
                label: 'Getting started',
                items: [
                  { label: 'Introduction', slug: 'refget' },
                  { label: 'Getting started tutorial', slug: 'refget/using-services/getting-started' },
                  { label: 'What are refget digests?', slug: 'refget/digests-explained' },
                  { label: 'What is RefgetStore?', slug: 'refget/refgetstore-explained' },
                  { label: 'How RefgetStore defers loading', slug: 'refget/lazy-loading-explained' },
                  { label: 'The readonly store and concurrency', slug: 'refget/readonly-store-explained' },
                  { label: 'How FASTA import works', slug: 'refget/fasta-import-explained' },
                  { label: 'Names, aliases, and identifiers', slug: 'refget/names-and-aliases-explained' },
                  { label: 'Understanding FHR metadata', slug: 'refget/fhr-metadata-explained' },
                  { label: 'The brickyard genome collection', slug: 'refget/genome-collections-explained' },
                  { label: 'HGVS parsing & VRS conversion', slug: 'refget/hgvs-explained' },
                  { label: 'What is RefgetTranscripts (reftx)?', slug: 'refget/reftx-explained' },
                ],
              },
              {
                label: 'Using refget services',
                items: [
                  { label: 'Computing digests', slug: 'refget/using-services/digests' },
                  { label: 'Python SequenceClient', slug: 'refget/using-services/sequence-client' },
                  { label: 'Python SequenceCollectionClient', slug: 'refget/using-services/seqcol-client' },
                ],
              },
              {
                label: 'Using RefgetStore',
                items: [
                  { label: 'RefgetStore tutorial', slug: 'refget/using-services/refgetstore' },
                  { label: 'Seqcol operations', slug: 'refget/using-services/seqcol-operations' },
                  { label: 'Working with aliases', slug: 'refget/using-services/aliases' },
                  { label: 'FHR metadata headers', slug: 'refget/using-services/fhr-metadata' },
                  { label: 'Exploring the genome store', slug: 'refget/using-services/genome-store' },
                  { label: 'Explore a store in your browser', slug: 'refget/using-services/explore-store' },
                  { label: 'Building an SSHash index', slug: 'refget/using-services/refgetstore-to-sshash' },
                ],
              },
              {
                label: 'BiocRefgetStore (R)',
                items: [
                  { label: 'Getting started', slug: 'refget/biocrefgetstore/getting-started' },
                  { label: 'Benchmark', slug: 'refget/biocrefgetstore/benchmark' },
                  { label: 'Reference', slug: 'refget/biocrefgetstore/reference' },
                ],
              },
              {
                label: 'Hosting refget services',
                items: [
                  { label: 'RefgetStore integration with refgenie', slug: 'refget/hosting-services/refgetstore-integration' },
                  { label: 'Serving a RefgetStore concurrently', slug: 'refget/hosting-services/howto-serve-refgetstore' },
                  { label: 'Adding a FastAPI router', slug: 'refget/hosting-services/fastapi_router' },
                  { label: 'RefgetDB Agent', slug: 'refget/hosting-services/agent' },
                  { label: 'Compliance testing', slug: 'refget/hosting-services/compliance' },
                ],
              },
              {
                label: 'Reference',
                items: [
                  { label: 'CLI', slug: 'refget/reference/cli' },
                  { label: 'CLI Configuration', slug: 'refget/reference/configuration' },
                  { label: 'REST API', link: 'https://seqcolapi.databio.org/docs' },
                  { label: 'Python API', slug: 'refget/reference/reference_docs' },
                  { label: 'Data models', slug: 'refget/reference/models' },
                  { label: 'RefgetStore format', slug: 'refget/reference/refgetstore-format' },
                  { label: 'RefgetStore retrieval flows', slug: 'refget/reference/refgetstore-retrieval-flows' },
                  { label: 'RefgetStore encoding', slug: 'refget/reference/encoding-comparison' },
                  { label: 'HGVS parsing API', slug: 'refget/hgvs-reference' },
                  { label: 'RefgetTranscripts (reftx) reference', slug: 'refget/reftx-reference' },
                  { label: 'Changelog', slug: 'refget/reference/changelog' },
                ],
              },
            ],
          },
          {
            label: 'Legacy',
            link: '/legacy/',
            icon: 'open-book',
            items: [
              {
                label: 'Refgenie (pre-1.0)',
                items: [
                  { label: 'Introduction', slug: 'legacy' },
                  { label: 'Demo videos', slug: 'legacy/demo_videos' },
                  { label: 'Overview', slug: 'legacy/overview' },
                  { label: 'Install and configure', slug: 'legacy/install' },
                  { label: 'Basic tutorial', slug: 'legacy/notebooks/tutorial' },
                  { label: 'Citing refgenie', slug: 'legacy/manuscripts' },
                  { label: 'Refer to assets', slug: 'legacy/asset_registry_paths' },
                  { label: 'Download pre-built assets', slug: 'legacy/pull' },
                  { label: 'Build assets', slug: 'legacy/build' },
                  { label: 'Add custom assets', slug: 'legacy/custom_assets' },
                  { label: 'Retrieve paths to assets', slug: 'legacy/seek' },
                  { label: 'Use asset tags', slug: 'legacy/tag' },
                  { label: 'Use aliases', slug: 'legacy/notebooks/aliases' },
                  { label: 'Populate refgenie paths', slug: 'legacy/populate' },
                  { label: 'Compare genomes', slug: 'legacy/compare' },
                  { label: 'Run my own asset server', slug: 'legacy/run_own_server' },
                  { label: 'Use refgenie from Python', slug: 'legacy/refgenconf' },
                  { label: 'Use refgenie in your pipeline', slug: 'legacy/code_snippets' },
                  { label: 'Use refgenie on the cloud', slug: 'legacy/remote' },
                  { label: 'Use refgenie with iGenomes', slug: 'legacy/igenomes' },
                  { label: 'Upgrade from config 0.3 to 0.4', slug: 'legacy/notebooks/config_upgrade_03_to_04' },
                  { label: 'Studies using refgenie', slug: 'legacy/uses_refgenie' },
                  { label: 'Genome configuration file', slug: 'legacy/genome_config' },
                  { label: 'Recipe specification', slug: 'legacy/recipe_specification' },
                  { label: 'Asset class specification', slug: 'legacy/asset_class_specification' },
                  { label: 'Glossary', slug: 'legacy/glossary' },
                  { label: 'Buildable assets', slug: 'legacy/available_assets' },
                  { label: 'Usage', slug: 'legacy/usage' },
                  { label: 'Refgenconf usage', slug: 'legacy/notebooks/refgenconf_usage' },
                  { label: 'FAQ', slug: 'legacy/faq' },
                  { label: 'Support', link: 'https://github.com/databio/refgenie/issues' },
                  { label: 'Contributing', slug: 'legacy/contributing' },
                  { label: 'Changelog', slug: 'legacy/changelog' },
                ],
              },
              {
                label: 'Refgenie server (pre-1.0)',
                items: [
                  { label: 'Intro', slug: 'legacy/refgenieserver' },
                ],
              },
            ],
          },
        ], {
          exclude: [
            '/index',
            '/.archive/**',
            '/decisions/**',
            '/refgenie/build_output',
            '/refgenie/code/**',
            '/refgenie/code_snippets',
            '/refgenie/refgenieserver',
            '/refget/reference/refgetstore-case-sensitivity',
            '/refget/using-services/create-ro-crate',
            '/refget/reference/refgetstore-ro-crate-profile',
            '/legacy/build_output',
            '/refgenie/server/data_channels_configuration',
          ],
        }),
      ],
    }),
  ],
});
