site_name: "Refgenie: next-generation reference genome management"

theme:
  logo: img/refgenie_bug_light.svg
  favicon: img/refgenie_bug.svg
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.sections
    # - navigation.expand
    - navigation.footer
    - navigation.indexes 
    - toc.follow
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"

extra_css:
  - stylesheets/extra.css

extra:
  generator: false  # turn off theme link

copyright: >
    <a class="" href="http://databio.org/">
      <img src="https://databio.org/images/logo/logo_databio_long.svg"
        style="height:60px;"
        alt="Databio logo">
    </a>

nav:
- Refgenie: 
  - Getting Started:
    - Introduction: refgenie/README.md
    - Demo videos: refgenie/demo_videos.md
    - Overview: refgenie/overview.md
    - Install and configure: refgenie/install.md
    - Basic tutorial: refgenie/notebooks/tutorial.ipynb
    - Citing refgenie: refgenie/manuscripts.md
  - How-to guides:
    - Refer to assets: refgenie/asset_registry_paths.md
    - Download pre-built assets: refgenie/pull.md
    - Build assets: refgenie/build.md
    - Add custom assets: refgenie/custom_assets.md
    - Retrieve paths to assets: refgenie/seek.md
    - Use asset tags: refgenie/tag.md
    - Use aliases: refgenie/notebooks/aliases.ipynb
    - Populate refgenie paths: refgenie/populate.md
    - Compare genomes: refgenie/compare.md
    - Run my own asset server: refgenie/refgenieserver.md
    - Use refgenie from Python: refgenie/refgenconf.md
    - Use refgenie in your pipeline: refgenie/code_snippets.md
    - Use refgenie on the cloud: refgenie/remote.md
    - Use refgenie with iGenomes: refgenie/igenomes.md
    - Upgrade from config 0.3 to 0.4: refgenie/notebooks/config_upgrade_03_to_04.ipynb
  - Reference:
    - Studies using refgenie: refgenie/uses_refgenie.md
    - Genome configuration file: refgenie/genome_config.md
    - Recipe: refgenie/recipe_specification.md
    - Asset class: refgenie/asset_class_specification.md
    - Glossary: refgenie/glossary.md
    - Buildable assets: refgenie/available_assets.md
    - Usage: refgenie/usage.md
    - Python API: refgenie/code/refgenconf-api.md
    - Refgenconf usage: refgenie/notebooks/refgenconf_usage.ipynb
    - FAQ: refgenie/faq.md
    - Support: https://github.com/databio/refgenie/issues
    - Contributing: refgenie/contributing.md
    - Changelog: refgenie/changelog.md
- Refgenie server:
  - Intro: refgenieserver/README.md
- Refgenie 1:
  - Getting Started:
    - Introduction: refgenie1/README.md
    - Overview: refgenie1/overview.md
    - Install: refgenie1/install.md
    - Configure: refgenie1/configuration.md
    - Citing refgenie: refgenie1/manuscripts.md
  - How-to guides:
    - Refer to assets: refgenie1/asset_registry_paths.md
    - Download pre-built assets: refgenie1/pull.md
    - Use refgenie from Python: refgenie1/notebooks/refgenie.ipynb
    - Use data channels: refgenie1/data_channels.md
    - Build assets: refgenie1/build.md
    - Download pre-built assets: refgenie1/pull.md
    - Retrieve paths to assets: refgenie1/seek.md
    - Managing asset groups and naming: refgenie1/naming_assets.md
    - Populate refgenie paths: refgenie1/populate.md
  - Reference:
    - Glossary: refgenie1/glossary.md
    - Studies using refgenie: refgenie1/uses_refgenie.md
    - Recipe: refgenie1/recipe_specification.md
    - Asset class: refgenie1/asset_class_specification.md
- Refgenie server 1:
  - Intro: refgenieserver1/README.md
  - Preparing servable assets at scale: refgenieserver1/archive_with_snakemake.md
  - Data channels: refgenieserver1/data_channels.md
  - Remotes: refgenieserver1/remotes.md
  - Persisting asset download stats: refgenieserver1/endpoint_hits_collector.md
  - Pagination and search: refgenieserver1/pagination_and_search.md
- Refget:
  - Getting started:
    - Getting started: refget/README.md
  - How-to guides:
    - Introduction: refget/introduction.md
    - Computing digests: refget/notebooks/digests.ipynb
    - GlobalRefgetStore: refget/notebooks/refgetstore.ipynb
    - Sequences Client: refget/notebooks/sequence-client.ipynb
    - Sequence Collections Client: refget/notebooks/seqcol-client.ipynb
    - RefgetDB Agent: refget/notebooks/agent.ipynb
    - Adding a fastAPI router: refget/fastapi_router.md
    - Compliance testing: refget/compliance.md
    - Command-line interface: refget/cli.md
  # - Outdated documentation:
  #   - Advanced tutorial: refget/code/advanced.md
  #   - Using local collections: refget/code/seqcol.md
  #   - Using local collections 2: refget/code/demo.md
  - Reference:
    - Changelog: refget/changelog.md
    - Refget Python API: refget/reference_docs.md
    - Pydantic models: refget/models.md


plugins:
- mkdocs-jupyter:
    include:
      - refget/notebooks/sequence-client.ipynb
      - refget/notebooks/seqcol-client.ipynb
      - refget/notebooks/agent.ipynb
      - refget/notebooks/digests.ipynb
      - refget/notebooks/refgetstore.ipynb
      - refgenie/notebooks/aliases.ipynb
      - refgenie/notebooks/config_upgrade_03_to_04.ipynb
      - refgenie/notebooks/refgenconf_usage.ipynb
      - refgenie/notebooks/tutorial.ipynb
      - refgenie1/notebooks/refgenie.ipynb
    ignore_h1_titles: True
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google  # Default to Google style
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_root_heading: true
          show_root_full_path: false
          show_source: true  # Optional: Show source code links
          show_signature: true  # Show method signatures
          show_if_no_docstring: false
          docstring_section_style: table  # Optional: Format style
          separate_signature: true  # Ensure __init__ appears clearly
          merge_init_into_class: true  # This ensures __init__ is documented

